### ISSUE TITLE
卡在教學影片1:00的地方

### ISSUE THREAD

**Issue by Darablue** [openupglobal/Blender-Chinese-Translation-Project#10]
Hello,

我是Hannah!

我是用Windows, 請問影片1分鐘的地方，"open with text editor", 我要用甚麼打開呢？謝謝 :)

**Comment by stansu** [comment]
> Hello,
> 
> 我是Hannah!
> 
> 我是用Windows, 請問影片1分鐘的地方，"open with text editor", 我要用甚麼打開呢？謝謝 :)

一般的文字編輯器就可以了

**Comment by Darablue** [comment]
我把英文複製過去了可是我不會上傳，可以麻煩你嗎？

**Comment by Darablue** [comment]
我不知道怎麼上傳檔案，就先上傳到這邊囉
[zh_TW_rev.zip](https://github.com/openupglobal/Blender-Chinese-Translation-Project/files/4349811/zh_TW_rev.zip)
