### ISSUE TITLE
這是我跟Jane 昨天晚上改的檔案

### ISSUE THREAD

**Issue by Darablue** [openupglobal/Blender-Chinese-Translation-Project#15]
我們把menu 的翻譯看了一次，然後遇到像是Export 這個字，我們把所有的 "導出" 都改成 "匯出" 。

然後我們看到一個錯字， 把 "重復" 改成 "重複"，這個是用replace all.

其他看到翻譯順序不對的地方就把動詞跟名詞的位置微調了一下。

我還是不會用pull request, 是不是要按照 github 最上方 "read the guide" 裡面所有的順序run過就能用pull request 上傳？

先上傳再這邊囉。

[Blender Chinese Translation.zip](https://github.com/openupglobal/Blender-Chinese-Translation-Project/files/4372654/Blender.Chinese.Translation.zip)

**Comment by stansu** [comment]
你可以google看看github的教學，在這之前我先用另一個帳號幫你pull request

**Comment by Darablue** [comment]
好

**Comment by stansu** [comment]
> 其他看到翻譯順序不對的地方就把動詞跟名詞的位置微調了一下。

這個在哪邊？

**Comment by pzfq12** [comment]
您好，贡献者。
我刚学习Blender不久，困惑在英语当中，而我没有Blender软件里的所有单词，需自己一个个去输入查找，而后注音标，我使用的是“欧路词典和幕布”，但这效率很低。我看到网上有自动翻译和注音标编程，因此想询问您这边有Blender软件里的所有单词吗？若有或没有，而我感谢您为Blender作贡献，让尔等小白能看懂。谢谢

**Comment by stansu** [comment]
> 您好，贡献者。
> 我刚学习Blender不久，困惑在英语当中，而我没有Blender软件里的所有单词，需自己一个个去输入查找，而后注音标，我使用的是“欧路词典和幕布”，但这效率很低。我看到网上有自动翻译和注音标编程，因此想询问您这边有Blender软件里的所有单词吗？若有或没有，而我感谢您为Blender作贡献，让尔等小白能看懂。谢谢

你可以下載我的Po檔案來看

**Comment by pzfq12** [comment]
好的，谢谢您
