### ISSUE TITLE
Eevee

### ISSUE THREAD

**Issue by stansu** [openupglobal/Blender-Chinese-Translation-Project#2]
可能的翻譯：

- 易益

**Comment by zerng07** [comment]
這類專用名詞直接沿用不需翻譯。
一般只有在廠商/組織有在當地申請中文商標時才翻譯，例如過去微軟有註冊視窗 (Windows)、樞紐分析表 (PiviotTable)，Bluetooth 聯盟註冊藍牙 (Bluetooth)，此時可用中文翻譯，否則皆視為專用名詞不更動。

**Comment by mwopus** [comment]
> 這類專用名詞直接沿用不需翻譯。
> 一般只有在廠商/組織有在當地申請中文商標時才翻譯，例如過去微軟有註冊視窗（Windows）中，樞紐分析表（PiviotTable），藍牙聯盟註冊藍牙（藍牙） ，此時可用中文翻譯，否則皆公認專用名詞不更動。

＂EEVEE＂如何翻譯成貼切達意的中文，是友善中文化的重點，不翻譯不是。
——找不出適合貼切的中文，可以暫時擱置。

**Comment by exn11140** [comment]
伊比

**Comment by bisechen** [comment]
> > 這類專用名詞直接沿用不需翻譯。
> > 一般只有在廠商/組織有在當地申請中文商標時才翻譯，例如過去微軟有註冊視窗（WINDOWS）中，樞紐分析表（PiviotTable），藍牙聯盟註冊藍牙（藍牙），此時可用的英語翻譯，否則皆公認專用名詞不更動。
> 
> 
> -找不出適合貼切的中文，可以暫時擱置。“ EEVEE”如何翻譯成貼切達意的中文，是友善中文化的重點，不翻譯不是。

有些東西確實就是沒有必要去翻譯，EEVEE這個字個人也覺得直接擱置比較恰當。

跟CYCLE那個非要翻成中文可是意思卻搞不好跟原本命名有落差的，這不是很奇怪的思路嗎？

**Comment by bisechen** [comment]
剛才把Blender 的各種語言都點一次看看，
目前 EEVEE 世界各種語言包括韓文、日文...都是維持 EEVEE 沒有給予翻譯的。
